# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: kfserving-config
#   namespace: kubeflow
# data:
#   ingressGateway: kubeflow/kubeflow-gateway


- op: replace
  path: /metadata/namespace
  value: kubeflow
- op: replace
  path: /data/ingressGateway
  value: kubeflow/kubeflow-gateway