apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubeflow/kfserving/releases/download/v0.6.1/kfserving.yaml

# patchesStrategicMerge:
# - patches/inferenceservice-config.yaml

patchesJson6902:
- target:
    version: v1
    kind: ConfigMap
    name: inferenceservice-config
    namespace: kubeflow
  path: patches/inferenceservice-config.yaml
- target:
    version: v1
    kind: ConfigMap
    name: kfserving-config
    namespace: kfserving-system
  path: patches/kfserving-config.yaml

images:
- name: gcr.io/kfserving/kfserving-controller
  newName: kfserving/kfserving-controller
  newTag: v0.6.1
  # digest: sha256:321f35c2cd934d449f9e1308ca45a8c9a92190bec83a33b37a18a6b4b649506a
- name: kfserving/models-web-app
  newName: kfserving/models-web-app
  newTag: v0.6.1
    # https://github.com/kserve/kserve/issues/1976#issuecomment-1007453347
    # KFServing releases v0.4.0/v0.4.1/v0.5.0/v0.5.1/v0.6.0 images have been backed up now under dockerhub kfserving. To prevent project suspension again in future as KServe working group no longer own the GCP kfserving project after moving out, we highly recommend updating kfserving controller image and inferenceservice-config configmap to use the images from dockerhub by changing the image prefix from gcr.io/kfserving to kfserving if you are using releases older than v0.6.1.
