kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBuvmRGFcffFa399EK2sfzZ205PzuWtpjToVxl9niplI1tLg1i6d4jLV8ImbM1jZrJ42FXC/dbvKYqM3QBEu3jk/IRvKsdREnFvUMoQwQKwXzPxfVOyGgkPDQ9yGVolsscwmBPu+2nOJHBOBHxt850ybBi5sgr9uXdDy5Dg3J7wZQng13QnF15A6osVXoPDi2o1FbVYRvYVrJbywRSv0J+c0C6NmtYCFGVvEat2+D3Em+j0fxmiheoMquibFj0N++zEOKmJI79/xCJlVaOEaogUOnwvtS4RtF5jpMtMU8yX3BKkm9arj4wTmQtrwBqeaSvk//MKl0vUH8L+63na3pGFCymKdic0iP4EoygDv1hC+uGziDFo7uXGandBGxugXv41j+Minx8ZbCN4Z+7E6B7bIZKsZ1L4h4fjoR8/bU5UIcirNU5cjvgbL0S6UvPofJRlT6Pr27PUH2sDojBJq9tuWuRvKBUSNK2fpZJIO0fjTQuYL+zaO2j82fOyUjWdELalJcr81Nz/B6DwdZ1l9zfoHBwziL9vNIwaOXcozKhZxHz67KfkZVD34QoHzdlVqgZRZfOTm3KMeTo6HAVg30S/TmWyFrMJBjtHzqRJ6nh0g0TuZcjJZLNbIBLSONl6SwLODNNjc9EQviWJKo0Dj+qpeecMwpJ+ktiWqHyzyxshDu7F+wpWnSwUP8dxLzbKk34qS/Ax
    admin-user: AgCPYmXreCliB29Tkqp0Sva3ItS6A+VHinMU1/S0EcZjjT1TA7tHxtSVooQ5aSO20GcyqVdpuJFULn+Me0KMAo5EjNHnZou/vVzG+49DoRlpgUaVe/oSYp5bUubM08t9OKXG0hw9geafIowEWiztMfnWn4BhRxVzzMtiRFjlvuC6qJuQyc7lifv6H2fPm1+WdsMt7+hk++M7OQ3Ys2zojEfh+Nyryv4GwKdV8N3WeOMc0R/+81fWzq5t82zwnB5zdUYeJiGPxBKNbbYIKPYhOEO2+BkjbknhDJTZa6SahlYN/3p2iT3Y1V2cnEqmjZMqmMaSWVR3iC4rnHb7lP3vDHPY92h5hoJ4fKmcGiuieFezz+Nf0FRbAKN9IXr8Ylcd+VIpvI7c/x6W8KtTbyrY0oBGalRHIADeI/+9ZsjIdWqgvGQiLTE6GCSUWuc7MvM/jwWdG+GUdexbFs8qJxlPgS1Rmg1ihqLzxYmpb4ujoyy25Op5RS6hzkWuPScSmaBhtU4pb11+uSh/Hj5zYRG/Pw4PLTkvyWflc8r1ZDCArDOegOxk1m86Tb9c3x9054b+HEk2eEgani3gnSXoFR9KqWBhoseXBZge8/S12jL08HH78zjvTXXAMc2NVFKGovCjufLwYXV6Nc6DinBiy/LGtq9AYNpYwxiOWrqe9ZOSbvtUhB3lju3Dh8xmrdVXHPIS4xcpFg==
