kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCviPrTyuXEWLfpjiPyi54vbdscoScn5aUJoYiX3hdU7fxIpswh6NCYZ83+sImH6gJGDmS381knh2a+sG9rM6hadT/jExIUca/M/JMjZ8owtC8jpoCNjDPyW1sxJTe2SEtoMjxCP10OWRj4vadZT7dM1lnsPl2yTE+6j87VyUtKtnEzOoiAvZxIooXkshGCc1vpEL3EZOSfERHVOp8XtPDUEHCEKAMWtnq5kges/rZAo8o7ws9Y/fmTrZUlb3aGfStqZ0+C7CAlc8rjBncW/YRrGyznNFCnSnJ4d7GPgMOromQ3cV3pBlANWj44tRRLglnzcQQsrb0YvrYTGFI16ECKf2zHHPQXM1AZlzMLFIVucfmqFN88/mKrikXLm/GZMuSemHCNYknLhpPQ5Ayx3YfajjU3O0iU3bqV5I6X4NkLpAmDf/zNPpwWVTqsnVIVIxLTOROOYjBnH/PCOodVidNBZAxpL207RTXwkVhfB/kXdr0qSmIZBixxiMwAclaJOsp6UNcB8awmVe9J6/g2yx3H/4sECaMIkjOVx66ltvWlz6pvGyCF9G7KU5x1TEgABFft1ojvrRXuAuNg5dMSwakI+DlO3NfqgpSCpJ9AKgnaYxF1Ypkd21afbu5oC514QlsDuAGdyi747soWQLvc7QIR9S7ZNNrcdOv5VvNGhK+gGLe9+Go8ldXOjzsi+/qFXrWVNh/p
    admin-user: AgBOtbgPOrbcA4iKjeLRlYYrG/TLDVu80e2YDI8c0hBlnRw3QY1tSg4S+tRIElBzRGyFtqQC3jlA2WEaIlyO0qCh9AQwC/3+uBO/nvv2xlx9HSZRbQKh0VKUVkvgRtcgry9/58KD8M5sM0lo0bCGToi/MFLm+bKvu9Tyuy7Gv9kWlLeKhGKe2aovVKBilG4l9P33tmsp3H4qjvOEgYf723E36UKy9ZVI2+Lt+tceZ8iefk9CTqmbnI8zqY/2fnpvyQF32IiCAJMJTJrIgLj3T+yxxwZIjEbtO2UtekHM6m8ASBMKWXZhpnutYkBnp/u7xLzlaZ+xiJJkLp+n5eCQSL17LpN+V4XwXoxErpd15jxqKd+vhJN+/lUwYkfMmZ1GMxVdTPScuLCLTeLPwL766nnpHI57WXFEUUim1a/kOuJi5iOi4SkJWoBVMjcyIjo6hzcBtatiKtXIiieDREETgldoI0XbQcuw2fR5OAdPN+u73XkqQazelkulRxHPcRJ8SSrurGZpujhp9pQdnNiGu/+RFqZCQAWYV1bvR7hjx2WwrAu1sfTLyOCadE/WON2vKOMG8q4JVNEpqdY/Sbq/lo5N2LLDQBbhL87IkSIMjluIjwLUIDuEbBCk95EWkKrOCbbzZ5X8WZt6iikbMtB+DujE1VaMWg9Qzf+XTMMSrPvxb6IOEGJXsaPf7NB5BdFLm0Fegg==
